[package]
name = "android-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
adb-client = { path = "../adb-client" }
ai-insight = { path = "../ai-insight" }
anyhow.workspace = true
crossbeam-channel.workspace = true
eframe.workspace = true
egui.workspace = true
egui_plot.workspace = true
egui_tiles.workspace = true
