[workspace]
members = ["crates/adb-client", "crates/android-terminal"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0.98"
crossbeam-channel = "0.5.15"
eframe = "0.31.1"
egui = "0.31.1"
egui_tiles = "0.12.0"
regex = "1.11.1"
thiserror = "2.0.12"
